export const RUNTIME_SECRET_KEYS: readonly [
  'SUPABASE_SECRET_KEY',
  'OPENROUTER_KEY',
  'ADMIN_PASS',
  'ADMIN_USER',
  'ADMIN_SESSION_SECRET',
  'RESEARCH_LAB_ALERT_DISCORD_WEBHOOK_URL',
  'RESEARCH_LAB_IMPROVEMENT_DISCORD_WEBHOOK_URL',
  'SOURCING_MODEL_GITHUB_TOKEN',
  'RESEARCH_LAB_ALERT_RESEND_API_KEY',
  'RESEARCH_LAB_ALERT_EMAIL_FROM',
  'RESEARCH_LAB_ALERT_EMAIL_TO',
  'RESEARCH_LAB_ALERT_EMAIL_REPLY_TO',
]

export function loadRuntimeSecretValues(): Promise<
  Record<(typeof RUNTIME_SECRET_KEYS)[number], string>
>
